### PR TITLE
#159965321 Create mockups for reporting an article

### PR DESCRIPTION
**Pull request by micahoriaso**
#### What does this PR do?
- Enable users to report an article

#### Description of the task to be completed?
- Give users the ability to report articles that violate the terms and conditions of Authors' Haven
#### How should this be manually tested?
```
$ git clone https://github.com/andela/ah-magnificent6.git
$ git checkout ft-report-article-mockups-159965321
$ cd ah-magnificent6/ui-mockups
$ brew install node
$ npm install
$ npm install gulp-cli -g
$ npm install gulp -D
$ gulp
On your browser navigate to http://localhost:3000/article.html
```

##### Screenshots
screen shot 2018-09-24 at 16 19 29

### CODE REVIEW

**Comment by meshack-mbuvi** [comment]
Please check your style sheet, seems rebasing was not complete

**Comment by micahoriaso** [comment]
> Please check your style sheet, seems rebasing was not complete

What is the exact problem with the stylesheet @meshack-mbuvi ?

**Comment by meshack-mbuvi** [comment]
image
That is what I see when I open the whole style.css file. Check the last line.

**Comment by Bileonaire** [comment]
I suggest we do not show the number of people who have reported the article, let us keep it confidential so that users may not be biased and read articles looking for why others have reported it. @micahoriaso

**Comment by micahoriaso** [comment]
@Bileonaire I have removed the report count.

**Pull request merged**
