### PR TITLE
#159965297 Integrate coverage with a badge.

### PR DESCRIPTION
**Pull request by meshack-mbuvi**
#### What does this PR do?
- Integrate coveralls with the repository.
#### Description of Task to be completed?
- Link repository with coveralls
- Add configuration file for *coveralls*; *.coveragerc* file
- Add badges to *README.md* file in the repository
#### How should this be manually tested?
- Click [here](https://github.com/andela/ah-magnificent6/tree/ch-integrate-coveralls-159965297) and check the badge on README.md file
#### What are the relevant pivotal tracker stories?
[Integrate Coverage with a badge](https://www.pivotaltracker.com/story/show/159965297)
.

### CODE REVIEW

**Comment by pabishai** [comment]
Where do I access the README.md. You have not provided a link to the branch.

**Comment by meshack-mbuvi** [comment]
@PAbishai I have done it now. Please confirm that you can access it.

**Comment by meshack-mbuvi** [comment]
@PAbishai I have done it already.

**Comment by pabishai** [comment]
@meshack-mbuvi. I can see the evidence of integration.

**Comment by mikenthiwa** [comment]
It is working as expected

**Pull request merged**
