### PR TITLE
#159965315 add mockups for article tags

### PR DESCRIPTION
**Pull request by meshack-mbuvi**
#### what does this pull request do
- Adds mockup for article tags
- ensure there are input fields for tags on new-article.html and edit-article.html files

#### Description of tasks to be completed
- Have input fields for article tags

#### How should this be tested manually
- Clone this repository
- Run the command `git checkout ft-article_tags_mockups-159965315`
- change directory to `ui-mockups` by executing `cd ui-mockups` in your terminal
- Do the following commands to set your environment for testing using your terminal
    - Install [node](Download | Node.js)
    - Run `npm install` to install all packages defined in `package.json` file
    - npm install gulp-cli -g
    - npm install gulp -D
- After executing above commands,type `gulp` and hit `[Enter]` button
- On your browser, visit the follwing pages
    - http://localhost:3000/new-article.html
    - http://localhost:3000/edit-article.html
#### Any background context you want to provide?
Having mockups is important in every API development because it helps to visualize how the user interface will look like in the finished product.

#### What are the relevant pivotal tracker stories?
[Tag articles](https://www.pivotaltracker.com/story/show/159965315)

#### screenshots
An input field for tags when creating a new article
image

An input field for tags when editing an article
image

### CODE REVIEW

**Comment by pabishai** [comment]
@meshack-mbuvi I think you added the wrong branch in the PR

**Comment by meshack-mbuvi** [comment]
Check again @PAbishai

**Comment by pabishai** [comment]
I suggest you increase the spacing between the tag and the upload button. This will make it look more cleaner

**Comment by meshack-mbuvi** [comment]
@PAbishai I have done it. Please confirm that it meets your expectations.

**Comment by mikenthiwa** [comment]
Looks good to me.

**Comment by parseen254** [comment]
@meshack-mbuvi on the edit-article page make sure the existing tags are values, not placeholders.

**Pull request merged**
