### PR TITLE
#159965305 Create Profile Mockups

### PR DESCRIPTION
**Pull request by pngg**
#### What does this PR do?
Create mockups for user profile

#### Description of Task to be completed
- Create `profile` and `update profile` pages

#### How should this be tested manually
- After cloning this repository, `git checkout ft-profile-mockups-159965305`
- cd into `ui-mockups`

- Using `gulp`
    - Install nodejs and npm
    - Run `npm install` to install all packages in the `package.json` file into `node_modules` folder
    - Run `npm install gulp-cli -g`
    - Run `gulp`

- On your browser, visit the following pages:
    - http://localhost:3000/profile.html
    - http://localhost:3000/edit_profile.html

#### Screenshots

`Profile page`
screenshot 2018-09-17 12 47 52

`Update profile page`
screenshot 2018-09-17 12 47 28

#### What are the relevant pivotal tracker stories?
[Users should be able to create their profiles](https://www.pivotaltracker.com/story/show/159965305)

### CODE REVIEW

**Comment by pabishai** [comment]
@pngg How are we to manually test this and see how it looks like?

**Comment by pngg** [comment]
> @pngg How are we to manually test this and see how it looks like?

Updated the PR

**Comment by pabishai** [comment]
@pngg Consider adding a way to navigate out of the profile window. Currently, I have to type out a different address

**Comment by pngg** [comment]
> @pngg Consider adding a way to navigate out of the profile window. Currently, I have to type out a different address

Added navigation for `Home`

**Comment by parseen254** [comment]
@pngg may thy screenshots be included.

**Pull request merged**
